### ISSUE TITLE
What to do

### ISSUE THREAD

**Issue by rogierslag** [inventid/landslide#1]
Hi @inventid/tech @inventid/sales 

In order to adequately show our feature set of Neo, I've taken the liberty of re-using an older demo site we had. It is currently located at https://landslide.inventid.nl/

In your opinion, what should we do before we can actively communicate this site to customers to show them what we offer?

**Comment by hiddeeysinksmeets** [comment]
This was what was previously the Follyven page right?

I expressed my doubts on this project earlier on already, as I think we tend to make a suggestion that we are a company able to make an entire webpage for you. The real thing we should be able to communicate to our customers is the demo webshop, as well as maybe a simplified page that shows the inegration of our webshop in a website (I think this is what you are after as well @rogierslag ?). Nevertheless, I don't think that an entire website should be available to express our services & products.

**Comment by rogierslag** [comment]
I think it should showcase how our products can be integrated. No more, no less. In case their is any doubt, just add a text explaining it to the bottom of the page.

Our product is one for which people can get very strong feelings once they see it in action, instead of some boring Excel sheets. We should aim to maximize that feeling

**Comment by hiddeeysinksmeets** [comment]
Still I think people are dumb and ignorant, so if they see this, they'll probably think that they can render website services from us as well.

We shouldn't make the page too much of it with other events and probaby implement more text on the fact that this is just a trial environment for customers of inventid.
